### PR TITLE
feat: Added sidebar navigation on labs page

### PR DESCRIPTION
**Pull request by sohamtembhurne**
Added navigation to sidebar on labs page by using `useMemo` hook.

### CODE REVIEW

**Comment by Debangan202Ok** [comment]
> Added navigation to sidebar on labs page by using `useMemo` hook. 

Hey @sohamtembhurne well done! It's look very nice. Currently I'm upgrading the project with nextjs. So for now I'm holding this pr. I will add this with the upgraded one. Btw nice work❤️

**Comment by sohamtembhurne** [comment]
> > Added navigation to sidebar on labs page by using `useMemo` hook.
> 
> Hey @sohamtembhurne well done! It's look very nice. Currently I'm upgrading the project with nextjs. So for now I'm holding this pr. I will add this with the upgraded one. Btw nice work❤️

It would be great if you could merge this under hacktoberfest. Thanks.

**Comment by sohamtembhurne** [comment]
Hey @Debangan202Ok, any updates on moving to NextJs ?

**Comment by Debangan202Ok** [comment]
> Hey @Debangan202Ok, any updates on moving to NextJs ?
>  

@sohamtembhurne actually I'm little bit busy for a week. I will give a update regarding this. Thanks for your message.

**Comment by sohamtembhurne** [comment]
> > Hey @Debangan202Ok, any updates on moving to NextJs ?
> 
> @sohamtembhurne actually I'm little bit busy for a week. I will give a update regarding this. Thanks for your message.

Any chance you could get this merged 😅 today ?
Thanks.

**Pull request merged**
