### PR TITLE
feat: added footer component

### LINKED ISSUE #1: Add a footer
The UI looks lame without a footer component
@Debangan202Ok assign me to this task and add the hacktoberfest tag

### PR DESCRIPTION
**Pull request by Toyin5**
Added a Footer componet
Resolves #1

### CODE REVIEW

**Comment by Debangan202Ok** [comment]
deploy-preview-2--data-structure-skill netlify app_
@Toyin5 well done! Can You Make the  footer container's Links and Social area more aligned and responsive ?

**Comment by Debangan202Ok** [comment]
> I'm so sorry. I was in a haste. I haven't committed the latest change
> Will do that soon

Sure! take your time🚀

**Comment by Debangan202Ok** [comment]
@Toyin5 are you working on it?

**Comment by Toyin5** [comment]
Yes
I will send a PR in an hour or less

**Comment by Debangan202Ok** [comment]
> Yes
> I will send a PR in an hour or less

Sure @Toyin5

**Comment by Toyin5** [comment]
Pls add the hacktoberfest-accepted tag
@Debangan202Ok

**Comment by Debangan202Ok** [comment]
@Toyin5 nice work. but it's look like same with the previous once. where is the alignment ? right side Links  look ugly

**Pull request merged**
