### PR TITLE
UI Changes

### PR DESCRIPTION
**Pull request by sohamtembhurne**
This is the fix for issue #4. Do take a look and a feedback would be great!

### CODE REVIEW

**Comment by Debangan202Ok** [comment]
> This is the fix for issue #4. Do take a look and a feedback would be great!

@sohamtembhurne  can you make the animation transition little bit smooth whilr scrolling?

**Comment by sohamtembhurne** [comment]
Do you have any particular type of transition in mind?

**Comment by Debangan202Ok** [comment]
> Do you have any particular type of transition in mind?

hey @sohamtembhurne 
1.i would like you to take a look at the animation on the GreenSock website (https://greensock.com/gsap/).
2.**Concerning the layout of containers:**
>   i want each container to occupy one viewport, and you want each container to automatically stay centered when scrolling.

**Comment by sohamtembhurne** [comment]
I made the transitions smoother.

**Comment by Debangan202Ok** [comment]
> I made the transitions smoother. 

@sohamtembhurne it's look fabulous. Can you make all the container same size?

**Comment by sohamtembhurne** [comment]
Fixed, you can merge the PR if there aren't any more changes

**Comment by Debangan202Ok** [comment]
> Fixed, you can merge the PR if there aren't any more changes

@sohamtembhurne look at this
deploy-preview-19--data-structure-skill netlify app_

i think you have to add some margins and use the responsive breakpoints for control the margin flow in different view ports

**Comment by sohamtembhurne** [comment]
This is happening for smaller screens due to not similiar text context. Let me try to find a fix.

**Comment by Debangan202Ok** [comment]
> This is happening for smaller screens due to not similiar text context. Let me try to find a fix.
>  

You can use breakpoint classes for larger margin will ne increase and for
Smaller as it is.i would like to
Recommend you to use developer tools om your browser. Bcuz this website want to be responsive for different devices at any scale.

**Comment by sohamtembhurne** [comment]
I have committed the changes you suggested

**Comment by sohamtembhurne** [comment]
This issue is due to the new sidebar functionality added, changes need to be done with the new button.

**Comment by sohamtembhurne** [comment]
> This issue is due to the new sidebar functionality added, changes need to be done with the new button.

Do add the hacktoberfest-accepted label

**Comment by sohamtembhurne** [comment]
> This issue is due to the new sidebar functionality added, changes need to be done with the new button.

Do add the hacktoberfest-accepted label

**Pull request merged**
