### PR TITLE
Queue function added

### PR DESCRIPTION
**Pull request by SpandanM110**
Iniially the queue feature was not added 
So here I present my queue feature in a new code file Queue.jsx and added in Body.jsx as well
Preview of the work:
image

Full View of the screen
image

Added content as well:
image

Hope You like my work and merge my PR 
Thanks and Regards
SpandanM110

### CODE REVIEW

**Comment by Debangan202Ok** [comment]
> Iniially the queue feature was not added 
> So here I present my queue feature in a new code file Queue.jsx and added in Body.jsx as well
> Preview of the work:
> image
> 
> 
> Full View of the screen
> image
> 
> Added content as well:
> image
> 
> Hope You like my work and merge my PR 
> Thanks and Regards
> SpandanM110

@SpandanM110 well done! Can you remove the queue operation from the stack page? Place it with the help of sidenav queue button.

**Comment by SpandanM110** [comment]
I have made changes and removed from the stack page.

**Comment by Debangan202Ok** [comment]
> I have made changes and removed from the stack page.

I saw what you done. But on clicking the sidenav queue section your queue operation is not reflecting. Check it

**Comment by SpandanM110** [comment]
I have tried whatever I could rest I will try my last it's in your hand hope you merge this or not.
Thanks and Regards
SpandanM110

**Comment by Debangan202Ok** [comment]
> I have tried whatever I could rest I will try my last it's in your hand hope you merge this or not.
> Thanks and Regards
> SpandanM110

@SpandanM110 Thanks for your attempt. Don't worry if you're unable to fix it; tell me. I will hold this pull request for now, fix it on my own, and then I will merge it.

Don't forget to give a star on your working repository.

**Pull request merged**
