### PR TITLE
Added a side navigation bar feature for data structures labs

### PR DESCRIPTION
**Pull request by Miran-Firdausi**
As of now its a responsive sidebar UI element as new data structure will be added, we can set the routes and links.

### CODE REVIEW

**Comment by Debangan202Ok** [comment]
@Miran-Firdausi please try to keep responsive in different view ports.
deploy-preview-21--data-structure-skill netlify app_labs_ (1)
try to align the icon with the proper container position. it's look ugly now

deploy-preview-21--data-structure-skill netlify app_labs_

look at the operation area.
please fix it.

**Comment by Miran-Firdausi** [comment]
what exactly you want me to do, I didn't get it?

**Comment by Miran-Firdausi** [comment]
image
You are talking about hamburger icon, right? Can you suggest me idea how to place it. or where to place it. Cause there is already a hamburger for navigating home and labs section.
and stack operation is not as wide as how it works div, right? I will fix it.

**Comment by Debangan202Ok** [comment]
> image You are talking about hamburger icon, right? Can you suggest me idea how to place it. or where to place it. Cause there is already a hamburger for navigating home and labs section. and stack operation is not as wide as how it works div, right? I will fix it.

try to align the icon with the starting position of the stack operation container. use developer tools to debug and fix the responsiveness.it may be help you.

**Comment by Miran-Firdausi** [comment]
sure, got it...

**Comment by Miran-Firdausi** [comment]
Check now. Tell me if anything else needs to be changed.

**Comment by Debangan202Ok** [comment]
> sure, got it...

@Miran-Firdausi nice work. But i think it need more enhancement. If wanna don with the current changes tell me. So i will merge it for now

**Comment by Miran-Firdausi** [comment]
Merge as of now. Will do more later.

**Comment by Debangan202Ok** [comment]
> Check now. Tell me if anything else needs to be changed.



Look at this it's not properly align with the container.

**Comment by Miran-Firdausi** [comment]
image
You want to align with this border, right?

**Comment by Debangan202Ok** [comment]
> Merge as of now. Will do more later.

Ahh!well. Doing this for now.

**Comment by Debangan202Ok** [comment]
> image
> You want to align with this border, right?

Yes

**Comment by Miran-Firdausi** [comment]
will do that...

**Comment by Debangan202Ok** [comment]
@Miran-Firdausi thank you for contribution. Don't forget to give a start on this repo😊.

**Comment by Miran-Firdausi** [comment]
Your welcome. Starred. Please add hactoberfest-accepted label.

**Comment by Debangan202Ok** [comment]
> Your welcome. Starred. Please add hactoberfest-accepted label.

Sure.

**Pull request merged**
